In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("AQI_Data.csv")

#to read csv file

In [15]:
df.head(8)
# to display first 8 rows

,City,Date,AQI,PM2.5,PM10,NO2,CO,O3,SO2
0,Delhi,2024-01-01,152,153,151,26.509131,1.581413,123.401530,25.062474
1,Delhi,2024-01-02,264,288,268,87.955853,1.242119,144.533790,5.926302
2,Delhi,2024-01-03,307,344,357,94.469744,0.101480,198.520196,32.786668
3,Delhi,2024-01-04,363,334,347,12.075618,1.097072,85.973585,7.099955
4,Delhi,2024-01-05,237,266,250,51.046299,1.591834,47.938019,28.140550
5,Delhi,2024-01-06,369,321,327,64.679037,0.423996,22.359803,47.699849
6,Delhi,2024-01-07,365,328,347,44.687485,0.130336,53.869827,15.846146
7,Delhi,2024-01-08,493,513,526,54.565922,0.165338,182.770876,16.645099

In [16]:
df.tail(5)

# to display the last 5 rows

,City,Date,AQI,PM2.5,PM10,NO2,CO,O3,SO2
2557,Pune,2024-12-27,419,448,462,26.701714,1.553582,86.973954,44.263423
2558,Pune,2024-12-28,252,202,182,19.920962,1.599821,41.939484,20.545087
2559,Pune,2024-12-29,365,414,410,80.815702,1.919950,39.982167,22.646297
2560,Pune,2024-12-30,253,269,285,66.231614,0.611800,63.966705,10.580135
2561,Pune,2024-12-31,95,140,117,99.505459,0.122817,112.774765,30.814997

In [9]:
df.info()

# to find d-types and number of null values in each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2562 entries, 0 to 2561
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   City    2562 non-null   object
 1   Date    2562 non-null   object
 2   AQI     2562 non-null   int64
 3   PM2.5   2562 non-null   int64
 4   PM10    2562 non-null   int64
 5   NO2     2562 non-null   float64
 6   CO      2562 non-null   float64
 7   O3      2562 non-null   float64
 8   SO2     2562 non-null   float64
dtypes: float64(4), int64(3), object(2)
memory usage: 180.3+ KB

In [11]:
import numpy as np

In [60]:
# to find meanAQI
mean_aqi = df.groupby('City')['AQI'].apply(np.mean)

In [61]:
print(mean_aqi)

City
Bangalore    279.543716
Chennai      274.314208
Delhi        279.153005
Hyderabad    280.355191
Kolkata      265.901639
Mumbai       287.797814
Pune         276.379781
Name: AQI, dtype: float64

In [62]:
# to find maxPM2.5

max_PM2 = df.groupby('City')['PM2.5'].apply(np.max)
print(max_PM2)

City
Bangalore    527
Chennai      530
Delhi        539
Hyderabad    543
Kolkata      535
Mumbai       519
Pune         532
Name: PM2.5, dtype: int64

In [63]:
#to find minPM10

min_PM10 = df.groupby('City')['PM2.5'].apply(np.min)
print(min_PM10)

City
Bangalore    14
Chennai       2
Delhi         5
Hyderabad    11
Kolkata      19
Mumbai       25
Pune         29
Name: PM2.5, dtype: int64

# SET = 3

In [64]:
#to find avgerage AQI

avg_aqi = df.groupby('City')['AQI'].mean()
print(avg_aqi)

City
Bangalore    279.543716
Chennai      274.314208
Delhi        279.153005
Hyderabad    280.355191
Kolkata      265.901639
Mumbai       287.797814
Pune         276.379781
Name: AQI, dtype: float64

In [65]:
# to find maximum PM2.5

max_PM21 = df.groupby('City')['PM2.5'].max()
print(max_PM21)

City
Bangalore    527
Chennai      530
Delhi        539
Hyderabad    543
Kolkata      535
Mumbai       519
Pune         532
Name: PM2.5, dtype: int64

In [66]:
# to find minimum PM10

min_PM10_1 = df.groupby('City')['PM2.5'].min()
print(min_PM10_1)

City
Bangalore    14
Chennai       2
Delhi         5
Hyderabad    11
Kolkata      19
Mumbai       25
Pune         29
Name: PM2.5, dtype: int64